persistence:
  enabled: true
  size: 20M

ingress:
  enabled: true
  type: traefik-crd
  hosts:
    - host: wbydc.io
      paths:
        - path: /
          pathType: Prefix

traefikCRD:
  entryPoints: 
    - http
